<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Wppus\Client\Serializer\ContentType;

use Psr\Http\Message\StreamInterface;
use Wppus\Client\Schema\SerializableInterface;

interface ContentTypeSerializerInterface
{
    const LITERAL_VALUE_KEY = '__literalResponseValue';

    public function encode(SerializableInterface $body): string;

    public function decode(StreamInterface $body): array;

    public function getMimeType(): string;
}
