<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Wppus\Client\Serializer\ContentType;

use Exception;

class SerializeException extends Exception
{
}
