<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Wppus\Client\Request\Mapper;

use Psr\Http\Message\RequestInterface as PsrRequestInterface;
use Wppus\Client\Request\RequestInterface;

interface RequestMapperInterface
{
    public function map(RequestInterface $request, string $url= ''): PsrRequestInterface;
}
