<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Wppus\Client\Request;

use Wppus\Client\Schema\SerializableInterface;

class GetLicensesCheckRequest implements RequestInterface
{
    private string $licenseKey;

    private ?array $allowedDomains = null;

    private ?string $packageSlug = null;

    private ?string $licenseSig = null;

    private string $contentType = '';

    public function __construct(string $licenseKey, string $packageSlug, string $licenseSig = '')
    {
        $this->licenseKey = $licenseKey;
        $this->licenseSig = $licenseSig;
        $this->allowedDomains = [$_SERVER['HTTP_HOST']];
        $this->setPackageSlug($packageSlug);
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function setPackageSlug(string $packageSlug): self
    {
        $this->packageSlug = $packageSlug;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'licenses/check';
    }

    public function getQueryParameters(): array
    {
        return array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['license_key' => $this->licenseKey, 'license_signature' => $this->licenseSig, 'allowed_domains' => [$this->allowedDomains], 'package_slug' => $this->packageSlug], static function ($value) {
            return null !== $value;
        }));
    }

    public function getRawQueryParameters(): array
    {
        return ['license_key' => $this->licenseKey, 'package_slug' => $this->packageSlug, 'license_signature' => $this->licenseSig ];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return [];
    }

    public function getBody()
    {
        return null;
    }
}
