<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Wppus\Client\Request;

use Wppus\Client\Schema\SerializableInterface;

class GetLicensesReadRequest implements RequestInterface
{
    private string $licenseKey;

    private ?array $allowedDomains = null;

    private ?string $packageSlug = null;

    private string $contentType = '';

    public function __construct(string $licenseKey)
    {
        $this->licenseKey = $licenseKey;
        $this->allowedDomains = [$SERVER['HTTP_HOST']];
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }  return $this;
    }

    public function setPackageSlug(string $packageSlug): self
    {
        $this->packageSlug = $packageSlug;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'wp-json/wppus/v1/licenses/read';
    }

    public function getQueryParameters(): array
    {
        return array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['license_key' => $this->licenseKey, 'allowed_domains' => $this->allowedDomains, 'package_slug' => $this->packageSlug], static function ($value) {
            return null !== $value;
        }));
    }

    public function getRawQueryParameters(): array
    {
        return ['license_key' => $this->licenseKey, 'allowed_domains' => $this->allowedDomains, 'package_slug' => $this->packageSlug];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return [];
    }

    public function getBody()
    {
        return null;
    }
}
