<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Wppus\Client\Request;

use JsonSerializable;
use Wppus\Client\Schema\PostLicensesRequestBody;

class PostLicensesActivateRequest implements RequestInterface
{
    private PostLicensesRequestBody $postLicensesActivateRequestBody;

    private string $contentType = 'application/json';

    public function __construct(PostLicensesRequestBody $postLicensesActivateRequestBody)
    {
        $this->postLicensesActivateRequestBody = $postLicensesActivateRequestBody;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getRoute(): string
    {
        return 'licenses/activate';
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return ['Content-Type' => $this->contentType];
    }

    /**
     * @return PostLicensesActivateRequestBody
     */
    public function getBody()
    {
        return $this->postLicensesActivateRequestBody;
    }
}
