<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Wppus\Client\Schema\Mapper;

use Wppus\Client\Schema\SerializableInterface;

interface SchemaMapperInterface
{
    /**
     * @return SerializableInterface
     */
    public function toSchema(array $payload);
}
