<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Wppus\Client\Response;

use DoclerLabs\ApiClientException\Factory\ResponseExceptionFactory;
use DoclerLabs\ApiClientException\UnexpectedResponseException;
use Psr\Http\Message\ResponseInterface;
use Wppus\Client\Serializer\BodySerializer;

class ResponseHandler
{
    /** @var BodySerializer */
    private $bodySerializer;

    /** @var ResponseExceptionFactory */
    private $responseExceptionFactory;

    public function __construct(BodySerializer $bodySerializer, ResponseExceptionFactory $exceptionFactory)
    {
        $this->bodySerializer           = $bodySerializer;
        $this->responseExceptionFactory = $exceptionFactory;
    }

    /**
     * @throws UnexpectedResponseException
     */
    public function handle(ResponseInterface $response): array
    {
        $statusCode = $response->getStatusCode();
        if ($statusCode >= 200 && $statusCode < 300) {
            return $this->bodySerializer->unserializeResponse($response);
        }
    
        throw $this->responseExceptionFactory->create(sprintf('code: %s message: %s, original message: %s ', $response->getStatusCode(), $response->getReasonPhrase(),  $this->bodySerializer->unserializeResponse($response)['message'] ), $response);
    }
}
