<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Wppus\Client;

use JsonSerializable;
use Pimple\Container;
use Pimple\Psr11\Container as Psr11Container;
use Psr\Container\ContainerInterface;
use Psr\Http\Client\ClientInterface;
use Http\Discovery\Psr18ClientDiscovery;

class Factory
{
    public static function create(ClientInterface $client = null, string $url = ''): WppusApiClient
    {
        // Discover a PSR-18 compatible HTTP client if no client is provided
        $client = $client ?? Psr18ClientDiscovery::find();

        return new WppusApiClient($client, self::initContainer(), $url);
    }

    private static function initContainer(): ContainerInterface
    {
        $pimpleContainer = new Container();
        $container       = new Psr11Container($pimpleContainer);
        $serviceProvider = new ServiceProvider();
        $serviceProvider->register($pimpleContainer);

        return $container;
    }

    public static function createRequestBody(array $params) :  JsonSerializable 
    {
       $container = self::initContainer();

        return ($container->get(JsonSerializable::class))->setParameters($params);
    }
}
